// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CustomPlugin.SpecflowPlugin.SampleTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SpecFlowFeature1")]
    public partial class SpecFlowFeature1Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SpecFlowFeature1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SpecFlowFeature1", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC66383: [AT] Warning message should appear on clicks of Continue button")]
        [NUnit.Framework.TimeoutAttribute(1000)]
        [NUnit.Framework.CategoryAttribute("HTMLDelivery")]
        [NUnit.Framework.IgnoreAttribute("Enterprise Integration Service - ExamScriptService, ExamAuditService")]
        public virtual void TC66383ATWarningMessageShouldAppearOnClicksOfContinueButton()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC66383: [AT] Warning message should appear on clicks of Continue button", null, new string[] {
                        "Timeout:1000",
                        "Ignore:Enterprise",
                        "Integration",
                        "Service",
                        "-",
                        "ExamScriptService,",
                        "ExamAuditService;",
                        "HTMLDelivery"});
#line 9
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC61751: Validate the Cancel functionality of Void dialog")]
        [NUnit.Framework.CategoryAttribute("HTMLDelivery")]
        [NUnit.Framework.TimeoutAttribute(555)]
        [NUnit.Framework.IgnoreAttribute("this is ignore")]
        [NUnit.Framework.TestCaseAttribute("Withdrawn", "1", null)]
        [NUnit.Framework.TestCaseAttribute("Partially Completed", "2", null)]
        public virtual void TC61751ValidateTheCancelFunctionalityOfVoidDialog(string value, string key, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "HTMLDelivery",
                    "ignore:this",
                    "is",
                    "ignore;",
                    "Timeout:555"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC61751: Validate the Cancel functionality of Void dialog", null, @__tags);
#line 14
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
 testRunner.Given("he is on Void dialog for a Mock Exam Name 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.And(string.Format("he selects {0} from void exam reason dropdown", value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.When("he clicks on Cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("Void Dialog should be closed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.And("Mock Exam Name 2 should display on the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC61752: Validate the Cancel functionality of Void dialog")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("Shiv")]
        [NUnit.Framework.TimeoutAttribute(555)]
        public virtual void TC61752ValidateTheCancelFunctionalityOfVoidDialog()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC61752: Validate the Cancel functionality of Void dialog", null, new string[] {
                        "Ignore",
                        "Shiv",
                        "Timeout:555"});
#line 30
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 31
 testRunner.Given("he is on Void dialog for a Mock Exam Name 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC61753: Validate the Cancel functionality of Void dialog")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("Shiva")]
        [NUnit.Framework.TimeoutAttribute(555)]
        public virtual void TC61753ValidateTheCancelFunctionalityOfVoidDialog()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC61753: Validate the Cancel functionality of Void dialog", null, new string[] {
                        "ignore",
                        "Shiva",
                        "Timeout:555"});
#line 36
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 37
 testRunner.Given("he is on Void dialog for a Mock Exam Name 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC61754: Validate the Cancel functionality of Void dialog")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("Shivendra")]
        [NUnit.Framework.TimeoutAttribute(555)]
        public virtual void TC61754ValidateTheCancelFunctionalityOfVoidDialog()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC61754: Validate the Cancel functionality of Void dialog", null, new string[] {
                        "ignore",
                        "Shivendra",
                        "Timeout:555"});
#line 42
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 43
 testRunner.Given("he is on Void dialog for a Mock Exam Name 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC61755: Validate the Cancel functionality of Void dialog")]
        [NUnit.Framework.CategoryAttribute("Shivendra")]
        [NUnit.Framework.TimeoutAttribute(555)]
        [NUnit.Framework.IgnoreAttribute("this is ignore")]
        public virtual void TC61755ValidateTheCancelFunctionalityOfVoidDialog()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC61755: Validate the Cancel functionality of Void dialog", null, new string[] {
                        "ignore:this",
                        "is",
                        "ignore;",
                        "Shivendra",
                        "Timeout:555"});
#line 48
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 49
 testRunner.Given("he is on Void dialog for a Mock Exam Name 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
